In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
pd.set_option('display.float_format', '{:.2f}'.format)
np.set_printoptions(formatter={'float_kind': "{:.2f}".format})
%config InlineBackend.figure_format = 'svg'

In [2]:
path = '/home/arthur/Project/GeekBrains/DB_research/!ADDS/hw_1/orders_20190822.csv'
df = pd.read_csv(path, sep=';')
df

            id_o  user_id     price      o_date
0        1234491   337544   539,000  01.01.2016
1        1234494   171642   153,300  01.01.2016
2        1234497   260596    55,300  01.01.2016
3        1234498  1105609   752,500  01.01.2016
4        1234500   982696  4410,000  01.01.2016
...          ...      ...       ...         ...
2002799  6945524  5806002   825,300  31.12.2017
2002800  6945526  5919142  4934,300  31.12.2017
2002801  6945527  1574166   804,300  31.12.2017
2002802  6945528  5919156  5019,700  31.12.2017
2002803  6945534  4801083   679,700  31.12.2017

[2002804 rows x 4 columns]

In [3]:
# задание соответствующих форматов столбцам
df['o_date'] = pd.to_datetime(df['o_date'], format='%d.%m.%Y')
df['year'] = df['o_date'].dt.year
df['price'] = df['price'].str.replace(',', '.').astype('float')
df['month'] = df['o_date'].dt.month

In [4]:
season_pivot = df.pivot_table(index=['year', 'month'], values='price', aggfunc=np.sum)
season_pivot = season_pivot.reset_index()
df = season_pivot.copy()
df

    year  month        price
0   2016      1  96812334.85
1   2016      2  95436530.70
2   2016      3 115270625.40
3   2016      4 139324010.70
4   2016      5 108587343.20
5   2016      6 116676502.60
6   2016      7 113191827.70
7   2016      8 139561892.40
8   2016      9 152917024.40
9   2016     10 211633380.70
10  2016     11 256654031.90
11  2016     12 258957148.10
12  2017      1 177191391.30
13  2017      2 161617657.60
14  2017      3 214789307.60
15  2017      4 197661209.90
16  2017      5 217075552.40
17  2017      6 184955837.50
18  2017      7 187225893.40
19  2017      8 205855839.70
20  2017      9 212034384.10
21  2017     10 280213678.50
22  2017     11 326694750.90
23  2017     12 372349285.70

## (1) Расчет значение тренда

In [5]:
# использование аналога excel-функции ЛИНЕЙН (LINEST) в numpy
Y = np.arange(1, df.shape[0]+1)
X = df['price'].to_numpy()
linest = np.polyfit(Y, X, 1)
b = linest[0]
a = linest[1]
b, a

(8430033.68672201, 83903222.30141279)

In [6]:
# рассчитываем значения тренда
df['id'] = Y
df['trend'] = df['id'] * b + a
df

    year  month        price  id        trend
0   2016      1  96812334.85   1  92333255.99
1   2016      2  95436530.70   2 100763289.67
2   2016      3 115270625.40   3 109193323.36
3   2016      4 139324010.70   4 117623357.05
4   2016      5 108587343.20   5 126053390.74
5   2016      6 116676502.60   6 134483424.42
6   2016      7 113191827.70   7 142913458.11
7   2016      8 139561892.40   8 151343491.80
8   2016      9 152917024.40   9 159773525.48
9   2016     10 211633380.70  10 168203559.17
10  2016     11 256654031.90  11 176633592.86
11  2016     12 258957148.10  12 185063626.54
12  2017      1 177191391.30  13 193493660.23
13  2017      2 161617657.60  14 201923693.92
14  2017      3 214789307.60  15 210353727.60
15  2017      4 197661209.90  16 218783761.29
16  2017      5 217075552.40  17 227213794.98
17  2017      6 184955837.50  18 235643828.66
18  2017      7 187225893.40  19 244073862.35
19  2017      8 205855839.70  20 252503896.04
20  2017      9 212034384.10  21 260933929.72
21  2017     10 280213678.50  22 269363963.41
22  2017     11 326694750.90  23 277793997.10
23  2017     12 372349285.70  24 286224030.78

## (2) Определение коэффициентов сезонности

In [7]:
# рассчитываем отклонение фактических значений от значений тренда
df['trend_delta'] = df['price'] / df['trend']
df

    year  month        price  id        trend  trend_delta
0   2016      1  96812334.85   1  92333255.99         1.05
1   2016      2  95436530.70   2 100763289.67         0.95
2   2016      3 115270625.40   3 109193323.36         1.06
3   2016      4 139324010.70   4 117623357.05         1.18
4   2016      5 108587343.20   5 126053390.74         0.86
5   2016      6 116676502.60   6 134483424.42         0.87
6   2016      7 113191827.70   7 142913458.11         0.79
7   2016      8 139561892.40   8 151343491.80         0.92
8   2016      9 152917024.40   9 159773525.48         0.96
9   2016     10 211633380.70  10 168203559.17         1.26
10  2016     11 256654031.90  11 176633592.86         1.45
11  2016     12 258957148.10  12 185063626.54         1.40
12  2017      1 177191391.30  13 193493660.23         0.92
13  2017      2 161617657.60  14 201923693.92         0.80
14  2017      3 214789307.60  15 210353727.60         1.02
15  2017      4 197661209.90  16 218783761.29         0.90
16  2017      5 217075552.40  17 227213794.98         0.96
17  2017      6 184955837.50  18 235643828.66         0.78
18  2017      7 187225893.40  19 244073862.35         0.77
19  2017      8 205855839.70  20 252503896.04         0.82
20  2017      9 212034384.10  21 260933929.72         0.81
21  2017     10 280213678.50  22 269363963.41         1.04
22  2017     11 326694750.90  23 277793997.10         1.18
23  2017     12 372349285.70  24 286224030.78         1.30

In [8]:
# Среднее отклонение для каждого месяца
avg_month_trend_delta = df.pivot_table(index='month', values='price',aggfunc=np.mean)
avg_month_trend_delta

             price
month
1     137001863.07
2     128527094.15
3     165029966.50
4     168492610.30
5     162831447.80
6     150816170.05
7     150208860.55
8     172708866.05
9     182475704.25
10    245923529.60
11    291674391.40
12    315653216.90

In [9]:
common_season_index = avg_month_trend_delta.mean().squeeze()
common_season_index

189278643.385438

In [10]:
avg_month_trend_delta['season_index'] = avg_month_trend_delta['price'] / common_season_index
avg_month_trend_delta

             price  season_index
month
1     137001863.07          0.72
2     128527094.15          0.68
3     165029966.50          0.87
4     168492610.30          0.89
5     162831447.80          0.86
6     150816170.05          0.80
7     150208860.55          0.79
8     172708866.05          0.91
9     182475704.25          0.96
10    245923529.60          1.30
11    291674391.40          1.54
12    315653216.90          1.67

## (3) Прогнозирование продаж

In [11]:
# задаем период, на который мы хотим рассчитать прогноз.
future = np.arange(df.shape[0]+1, df.shape[0]+1+12)
df_future = pd.DataFrame(index=future)

# рассчитываем значения трена для будущих периодов
df_future['f_trend'] = df_future.index * b + a
df_future['month'] = np.arange(1,13)

# подтягиваем коэффициены сезонности
df_future = df_future.merge(avg_month_trend_delta, left_on='month', right_index=True)
df_future

        f_trend  month        price  season_index
25 294654064.47      1 137001863.07          0.72
26 303084098.16      2 128527094.15          0.68
27 311514131.84      3 165029966.50          0.87
28 319944165.53      4 168492610.30          0.89
29 328374199.22      5 162831447.80          0.86
30 336804232.90      6 150816170.05          0.80
31 345234266.59      7 150208860.55          0.79
32 353664300.28      8 172708866.05          0.91
33 362094333.96      9 182475704.25          0.96
34 370524367.65     10 245923529.60          1.30
35 378954401.34     11 291674391.40          1.54
36 387384435.02     12 315653216.90          1.67

In [12]:
# Рассчитываем прогноз
df_future['f_price'] = df_future['f_trend'] * df_future['season_index']
df_future

        f_trend  month        price  season_index      f_price
25 294654064.47      1 137001863.07          0.72 213273695.72
26 303084098.16      2 128527094.15          0.68 205805143.79
27 311514131.84      3 165029966.50          0.87 271605743.91
28 319944165.53      4 168492610.30          0.89 284808822.78
29 328374199.22      5 162831447.80          0.86 282491702.83
30 336804232.90      6 150816170.05          0.80 268363739.06
31 345234266.59      7 150208860.55          0.79 273973042.49
32 353664300.28      8 172708866.05          0.91 322703920.37
33 362094333.96      9 182475704.25          0.96 349080157.24
34 370524367.65     10 245923529.60          1.30 481410151.01
35 378954401.34     11 291674391.40          1.54 583960727.96
36 387384435.02     12 315653216.90          1.67 646027152.91

## (4) Проверка результата

##### Фактический результат
1801 256798898  
1802 232640416  
1803 267994924  
1804 262849522  
1805 276933049  
1806 251486085  
1807 250559778  
1808 261724749  
1809 276675505  
1810 287647539  
1811 363102609  
1812 422386052634

In [13]:
df_future['real_price'] = [256798898, 232640416, 267994924, 262849522, 276933049, 251486085, 250559778, 261724749, 276675505, 287647539, 363102609, 422386052]
df_future

        f_trend  month        price  season_index      f_price  real_price
25 294654064.47      1 137001863.07          0.72 213273695.72   256798898
26 303084098.16      2 128527094.15          0.68 205805143.79   232640416
27 311514131.84      3 165029966.50          0.87 271605743.91   267994924
28 319944165.53      4 168492610.30          0.89 284808822.78   262849522
29 328374199.22      5 162831447.80          0.86 282491702.83   276933049
30 336804232.90      6 150816170.05          0.80 268363739.06   251486085
31 345234266.59      7 150208860.55          0.79 273973042.49   250559778
32 353664300.28      8 172708866.05          0.91 322703920.37   261724749
33 362094333.96      9 182475704.25          0.96 349080157.24   276675505
34 370524367.65     10 245923529.60          1.30 481410151.01   287647539
35 378954401.34     11 291674391.40          1.54 583960727.96   363102609
36 387384435.02     12 315653216.90          1.67 646027152.91   422386052

In [14]:
df_future.set_index('month')[['f_price', 'real_price']]

           f_price  real_price
month
1     213273695.72   256798898
2     205805143.79   232640416
3     271605743.91   267994924
4     284808822.78   262849522
5     282491702.83   276933049
6     268363739.06   251486085
7     273973042.49   250559778
8     322703920.37   261724749
9     349080157.24   276675505
10    481410151.01   287647539
11    583960727.96   363102609
12    646027152.91   422386052

In [15]:
sns.set_theme()
plt.figure(figsize=(12,8))
sns.lineplot(data=df_future.set_index('month')[['f_price', 'real_price']])